name: connect_guard
description: "A smart network awareness widget that handles offline states, internet connectivity checks, and automatic UI switching."
version: 0.0.1
homepage: https://github.com/tekle-eyesus/connect_guard
repository: https://github.com/tekle-eyesus/connect_guard
issue_tracker: https://github.com/tekle-eyesus/connect_guard/issues

environment:
  sdk: ^3.6.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  connectivity_plus: ^7.0.0
  internet_connection_checker_plus: ^2.9.1+1
  rxdart: ^0.28.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter: